console.info("Agrego funcionalidades");
console.info("Agrego funcionalidades");
console.info("Agrego funcionalidades");
console.info("Agrego funcionalidades");
console.info("Agrego funcionalidades");
console.info("Agrego funcionalidades");
console.info("Agrego funcionalidades");
console.info("Agrego funcionalidades");
console.log("Corregido");
console.info("sigo trabajando");
console.info("sigo trabajando");
console.info("sigo trabajando");
console.info("sigo trabajando");